### ISSUE TITLE
Authentication with Google Auth

### ISSUE THREAD

**Issue by brehen** [Overhuset/overhuset.no#1]
As the intranett is made for the people working in the companies underneath "Overhuset", we want to authenticate all users who try to access our intranett page.

The url is https://overhuset.no/intranett, and any access to this page and underlying subpages should be limited to logged in users with the following email domains.

These are the companies: 

'arktekk',
'boitano',
'edisys',
'fink',
'forse',
'jpro',
'kodemaker',
'sannsyn',
'uptime',
'zenior'

**Comment by AnndreaD** [comment]
donzo
